//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject.LM_TestDev_WS_Reference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/", ConfigurationName="LM_TestDev_WS_Reference.LM_TestDev_WSSoap")]
    public interface LM_TestDev_WSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/Fibonacci", ReplyAction="*")]
        decimal Fibonacci(int n);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément xml de l'espace de noms http://localhost/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/XmlToJson", ReplyAction="*")]
        UnitTestProject.LM_TestDev_WS_Reference.XmlToJsonResponse XmlToJson(UnitTestProject.LM_TestDev_WS_Reference.XmlToJsonRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément xml de l'espace de noms http://localhost/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/XmlToJsonWithFormatting", ReplyAction="*")]
        UnitTestProject.LM_TestDev_WS_Reference.XmlToJsonWithFormattingResponse XmlToJsonWithFormatting(UnitTestProject.LM_TestDev_WS_Reference.XmlToJsonWithFormattingRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlToJsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlToJson", Namespace="http://localhost/", Order=0)]
        public UnitTestProject.LM_TestDev_WS_Reference.XmlToJsonRequestBody Body;
        
        public XmlToJsonRequest() {
        }
        
        public XmlToJsonRequest(UnitTestProject.LM_TestDev_WS_Reference.XmlToJsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class XmlToJsonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public XmlToJsonRequestBody() {
        }
        
        public XmlToJsonRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlToJsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlToJsonResponse", Namespace="http://localhost/", Order=0)]
        public UnitTestProject.LM_TestDev_WS_Reference.XmlToJsonResponseBody Body;
        
        public XmlToJsonResponse() {
        }
        
        public XmlToJsonResponse(UnitTestProject.LM_TestDev_WS_Reference.XmlToJsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class XmlToJsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XmlToJsonResult;
        
        public XmlToJsonResponseBody() {
        }
        
        public XmlToJsonResponseBody(string XmlToJsonResult) {
            this.XmlToJsonResult = XmlToJsonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlToJsonWithFormattingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlToJsonWithFormatting", Namespace="http://localhost/", Order=0)]
        public UnitTestProject.LM_TestDev_WS_Reference.XmlToJsonWithFormattingRequestBody Body;
        
        public XmlToJsonWithFormattingRequest() {
        }
        
        public XmlToJsonWithFormattingRequest(UnitTestProject.LM_TestDev_WS_Reference.XmlToJsonWithFormattingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class XmlToJsonWithFormattingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool isOutputIndented;
        
        public XmlToJsonWithFormattingRequestBody() {
        }
        
        public XmlToJsonWithFormattingRequestBody(string xml, bool isOutputIndented) {
            this.xml = xml;
            this.isOutputIndented = isOutputIndented;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlToJsonWithFormattingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlToJsonWithFormattingResponse", Namespace="http://localhost/", Order=0)]
        public UnitTestProject.LM_TestDev_WS_Reference.XmlToJsonWithFormattingResponseBody Body;
        
        public XmlToJsonWithFormattingResponse() {
        }
        
        public XmlToJsonWithFormattingResponse(UnitTestProject.LM_TestDev_WS_Reference.XmlToJsonWithFormattingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class XmlToJsonWithFormattingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XmlToJsonWithFormattingResult;
        
        public XmlToJsonWithFormattingResponseBody() {
        }
        
        public XmlToJsonWithFormattingResponseBody(string XmlToJsonWithFormattingResult) {
            this.XmlToJsonWithFormattingResult = XmlToJsonWithFormattingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LM_TestDev_WSSoapChannel : UnitTestProject.LM_TestDev_WS_Reference.LM_TestDev_WSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LM_TestDev_WSSoapClient : System.ServiceModel.ClientBase<UnitTestProject.LM_TestDev_WS_Reference.LM_TestDev_WSSoap>, UnitTestProject.LM_TestDev_WS_Reference.LM_TestDev_WSSoap {
        
        public LM_TestDev_WSSoapClient() {
        }
        
        public LM_TestDev_WSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LM_TestDev_WSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LM_TestDev_WSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LM_TestDev_WSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal Fibonacci(int n) {
            return base.Channel.Fibonacci(n);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestProject.LM_TestDev_WS_Reference.XmlToJsonResponse UnitTestProject.LM_TestDev_WS_Reference.LM_TestDev_WSSoap.XmlToJson(UnitTestProject.LM_TestDev_WS_Reference.XmlToJsonRequest request) {
            return base.Channel.XmlToJson(request);
        }
        
        public string XmlToJson(string xml) {
            UnitTestProject.LM_TestDev_WS_Reference.XmlToJsonRequest inValue = new UnitTestProject.LM_TestDev_WS_Reference.XmlToJsonRequest();
            inValue.Body = new UnitTestProject.LM_TestDev_WS_Reference.XmlToJsonRequestBody();
            inValue.Body.xml = xml;
            UnitTestProject.LM_TestDev_WS_Reference.XmlToJsonResponse retVal = ((UnitTestProject.LM_TestDev_WS_Reference.LM_TestDev_WSSoap)(this)).XmlToJson(inValue);
            return retVal.Body.XmlToJsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestProject.LM_TestDev_WS_Reference.XmlToJsonWithFormattingResponse UnitTestProject.LM_TestDev_WS_Reference.LM_TestDev_WSSoap.XmlToJsonWithFormatting(UnitTestProject.LM_TestDev_WS_Reference.XmlToJsonWithFormattingRequest request) {
            return base.Channel.XmlToJsonWithFormatting(request);
        }
        
        public string XmlToJsonWithFormatting(string xml, bool isOutputIndented) {
            UnitTestProject.LM_TestDev_WS_Reference.XmlToJsonWithFormattingRequest inValue = new UnitTestProject.LM_TestDev_WS_Reference.XmlToJsonWithFormattingRequest();
            inValue.Body = new UnitTestProject.LM_TestDev_WS_Reference.XmlToJsonWithFormattingRequestBody();
            inValue.Body.xml = xml;
            inValue.Body.isOutputIndented = isOutputIndented;
            UnitTestProject.LM_TestDev_WS_Reference.XmlToJsonWithFormattingResponse retVal = ((UnitTestProject.LM_TestDev_WS_Reference.LM_TestDev_WSSoap)(this)).XmlToJsonWithFormatting(inValue);
            return retVal.Body.XmlToJsonWithFormattingResult;
        }
    }
}
