//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject.LM_TestDev_WS_Reference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/", ConfigurationName="LM_TestDev_WS_Reference.LM_TestDev_WSSoap")]
    public interface LM_TestDev_WSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/Fibonacci", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        decimal Fibonacci(int n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/FibonacciJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void FibonacciJSON(int n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/XmlToJson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string XmlToJson(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/XmlToJsonWithFormatting", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string XmlToJsonWithFormatting(string xml, bool isOutputIndented);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LM_TestDev_WSSoapChannel : UnitTestProject.LM_TestDev_WS_Reference.LM_TestDev_WSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LM_TestDev_WSSoapClient : System.ServiceModel.ClientBase<UnitTestProject.LM_TestDev_WS_Reference.LM_TestDev_WSSoap>, UnitTestProject.LM_TestDev_WS_Reference.LM_TestDev_WSSoap {
        
        public LM_TestDev_WSSoapClient() {
        }
        
        public LM_TestDev_WSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LM_TestDev_WSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LM_TestDev_WSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LM_TestDev_WSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal Fibonacci(int n) {
            return base.Channel.Fibonacci(n);
        }
        
        public void FibonacciJSON(int n) {
            base.Channel.FibonacciJSON(n);
        }
        
        public string XmlToJson(string xml) {
            return base.Channel.XmlToJson(xml);
        }
        
        public string XmlToJsonWithFormatting(string xml, bool isOutputIndented) {
            return base.Channel.XmlToJsonWithFormatting(xml, isOutputIndented);
        }
    }
}
